# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: UsmanAkram.FastDL
PackageVersion: 1.8
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Usman-akram-2003/FastDL/releases/download/v1.8/FastDL-Setup.exe
  InstallerSha256: F4CC1F77CD3EE6E322F7AB9AA52955CB9D6A8DA6B9F29B29171C1975255CC02A
ManifestType: installer
ManifestVersion: 1.12.0
